### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by mbr0wn**
Clarify usage of DCO, and request users sign off their commits.

Signed-off-by: Martin Braun <martin.braun@ni.com>

- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/<reponame>/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by benmont** [comment]
@mbr0wn : The pull request template (https://github.com/ni/Github-Repo-Template/blob/master/.github/PULL_REQUEST_TEMPLATE.md) also includes a checkbox to ensure the submitter has read and agrees to the DCO, as it is contained in the CONTRIBUTING file. Your change would add two mechanisms for sign-off. Should we remove the other one? What do other GitHub projects do here?

**Comment by mbr0wn** [comment]
`Signed-off-by` is definitely more common than a checkbox, and it transcends GitHub and bakes the sign-off into the hashed commits.
On top of that, we can recommend a GitHub Action that auto-checks the existence of the `Signed-off-by` line. For the open source projects, Actions are free anyway so we maybe even add the Action to the template.

**Comment by mbr0wn** [comment]
Agree it's redundant. I'll remove the checkbox.

**Comment by mbr0wn** [comment]
Side note: `Signed-off-by` allows multiple signatures.

**Comment by benmont** [comment]
> On top of that, we can recommend a GitHub Action that auto-checks the existence of the `Signed-off-by` line. For the open source projects, Actions are free anyway so we maybe even add the Action to the template.

I like the idea of adding the Action to the template.

**Pull request merged**
